export const APP_TIME_ZONE = "Europe/Paris";

export const DEFAULT_SERVICE_OPENING_TIME = "18:30";
export const DEFAULT_SERVICE_CLOSING_TIME = "21:30";

export const SERVICE_OPENING_TIME = DEFAULT_SERVICE_OPENING_TIME;
export const SERVICE_CLOSING_TIME = DEFAULT_SERVICE_CLOSING_TIME;

export const DEFAULT_SLOT_STEP_MINUTES = 5;