ALTER TABLE pizzas
  ADD COLUMN IF NOT EXISTS ingredients TEXT NOT NULL DEFAULT '';

ALTER TABLE pizzas
  ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';

ALTER TABLE pizzas
  ADD COLUMN IF NOT EXISTS allergens TEXT NOT NULL DEFAULT '';

ALTER TABLE pizzas
  ADD COLUMN IF NOT EXISTS photo_path TEXT;